
exclude: ["Gemfile","Gemfile.lock","README.md","CNAME"]

# Site settings
author; Ann Noble
name: Inspiration for change.
title: Inspiration for change
email: ann@inspirationforchange.co.uk
description: The home page for inspiration for change | Life Retuning- Utying the knots of your life.

baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty

relative_permalinks: false
