exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
include: ["_pages"]
author: Ann Noble
name: Inspiration for change.
title: Inspiration for change
email: "ann@inspirationforchange.co.uk"
description: "The home page for inspiration for change | Life Retuning- Utying the knots of your life."
image: "http://www.inspirationforchange.co.uk/images/logo.png"
baseurl: ""
url: ""
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: '_pages'
    values:
      layout: 'page'
