exclude:
  - README.md
  - CNAME

gems:
  - jekyll-feed
  
author: Ann Noble
name: Inspiration for change.
title: Inspiration for change
email: "ann@inspirationforchange.co.uk"
description: "The home page for inspiration for change | Life Retuning- Utying the knots of your life."
image: "http://www.inspirationforchange.co.uk/images/logo.png"
baseurl: ""
url: ""
markdown: kramdown
permalink: pretty
excerpt_separator: "<!--more-->"

defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'page'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      permalink: "/posts/:title/"

social:
  - name: facebook
    url: "https://facebook.com/soulbalancetherapy"
  - name: rss
    url: "/feed.xml"
